/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeAMentorRouteImport } from './routes/become-a-mentor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as MentorApplyRouteImport } from './routes/mentor/apply'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin/audit-logs'
import { Route as AuthenticatedAdminBookingQueueRouteImport } from './routes/_authenticated/admin/booking-queue'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminDemoQueueRouteImport } from './routes/_authenticated/admin/demo-queue'
import { Route as AuthenticatedAdminMentorApplicationsRouteImport } from './routes/_authenticated/admin/mentor-applications'
import { Route as AuthenticatedAdminNotificationBroadcastsRouteImport } from './routes/_authenticated/admin/notification-broadcasts'
import { Route as AuthenticatedAdminSlotManagementRouteImport } from './routes/_authenticated/admin/slot-management'
import { Route as AuthenticatedAdminSubscriptionManagementRouteImport } from './routes/_authenticated/admin/subscription-management'
import { Route as AuthenticatedAdminSubscriptionPlansRouteImport } from './routes/_authenticated/admin/subscription-plans'
import { Route as AuthenticatedAdminSupportTicketsRouteImport } from './routes/_authenticated/admin/support-tickets'
import { Route as AuthenticatedMentorApplicationRouteImport } from './routes/_authenticated/mentor/application'
import { Route as AuthenticatedMentorAvailabilityRouteImport } from './routes/_authenticated/mentor/availability'
import { Route as AuthenticatedMentorCalendarRouteImport } from './routes/_authenticated/mentor/calendar'
import { Route as AuthenticatedMentorDashboardRouteImport } from './routes/_authenticated/mentor/dashboard'
import { Route as AuthenticatedMentorProfileRouteImport } from './routes/_authenticated/mentor/profile'
import { Route as AuthenticatedMentorRequestsRouteImport } from './routes/_authenticated/mentor/requests'
import { Route as AuthenticatedMentorResourcesRouteImport } from './routes/_authenticated/mentor/resources'
import { Route as AuthenticatedMentorSessionsRouteImport } from './routes/_authenticated/mentor/sessions'
import { Route as AuthenticatedStudentCheckoutRouteImport } from './routes/_authenticated/student/checkout'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/student/dashboard'
import { Route as AuthenticatedStudentDemoConversionRouteImport } from './routes/_authenticated/student/demo-conversion'
import { Route as AuthenticatedStudentDemoSessionRouteImport } from './routes/_authenticated/student/demo-session'
import { Route as AuthenticatedStudentExploreRouteImport } from './routes/_authenticated/student/explore'
import { Route as AuthenticatedStudentHistoryRouteImport } from './routes/_authenticated/student/history'
import { Route as AuthenticatedStudentPricingRouteImport } from './routes/_authenticated/student/pricing'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/student/profile'
import { Route as AuthenticatedStudentResourcesRouteImport } from './routes/_authenticated/student/resources'
import { Route as AuthenticatedStudentSessionsRouteImport } from './routes/_authenticated/student/sessions'
import { Route as AuthenticatedStudentStreakRouteImport } from './routes/_authenticated/student/streak'
import { Route as AuthenticatedStudentStudentSettingsRouteImport } from './routes/_authenticated/student/student-settings'
import { Route as AuthenticatedStudentSubscriptionSlotsRouteImport } from './routes/_authenticated/student/subscription-slots'
import { Route as AuthenticatedStudentSubscriptionsRouteImport } from './routes/_authenticated/student/subscriptions'
import { Route as AuthenticatedAdminMentorApplicationsIdRouteImport } from './routes/_authenticated/admin/mentor-applications/$id'
import { Route as AuthenticatedMentorSessionIdRouteImport } from './routes/_authenticated/mentor/session.$id'
import { Route as AuthenticatedStudentMentorIdRouteImport } from './routes/_authenticated/student/mentor.$id'
import { Route as AuthenticatedStudentSessionIdRouteImport } from './routes/_authenticated/student/session.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAMentorRoute = BecomeAMentorRouteImport.update({
  id: '/become-a-mentor',
  path: '/become-a-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const MentorApplyRoute = MentorApplyRouteImport.update({
  id: '/mentor/apply',
  path: '/mentor/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/admin/audit-logs',
    path: '/admin/audit-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBookingQueueRoute =
  AuthenticatedAdminBookingQueueRouteImport.update({
    id: '/admin/booking-queue',
    path: '/admin/booking-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDemoQueueRoute =
  AuthenticatedAdminDemoQueueRouteImport.update({
    id: '/admin/demo-queue',
    path: '/admin/demo-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMentorApplicationsRoute =
  AuthenticatedAdminMentorApplicationsRouteImport.update({
    id: '/admin/mentor-applications',
    path: '/admin/mentor-applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotificationBroadcastsRoute =
  AuthenticatedAdminNotificationBroadcastsRouteImport.update({
    id: '/admin/notification-broadcasts',
    path: '/admin/notification-broadcasts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSlotManagementRoute =
  AuthenticatedAdminSlotManagementRouteImport.update({
    id: '/admin/slot-management',
    path: '/admin/slot-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSubscriptionManagementRoute =
  AuthenticatedAdminSubscriptionManagementRouteImport.update({
    id: '/admin/subscription-management',
    path: '/admin/subscription-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSubscriptionPlansRoute =
  AuthenticatedAdminSubscriptionPlansRouteImport.update({
    id: '/admin/subscription-plans',
    path: '/admin/subscription-plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSupportTicketsRoute =
  AuthenticatedAdminSupportTicketsRouteImport.update({
    id: '/admin/support-tickets',
    path: '/admin/support-tickets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorApplicationRoute =
  AuthenticatedMentorApplicationRouteImport.update({
    id: '/mentor/application',
    path: '/mentor/application',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorAvailabilityRoute =
  AuthenticatedMentorAvailabilityRouteImport.update({
    id: '/mentor/availability',
    path: '/mentor/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorCalendarRoute =
  AuthenticatedMentorCalendarRouteImport.update({
    id: '/mentor/calendar',
    path: '/mentor/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorDashboardRoute =
  AuthenticatedMentorDashboardRouteImport.update({
    id: '/mentor/dashboard',
    path: '/mentor/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorProfileRoute =
  AuthenticatedMentorProfileRouteImport.update({
    id: '/mentor/profile',
    path: '/mentor/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorRequestsRoute =
  AuthenticatedMentorRequestsRouteImport.update({
    id: '/mentor/requests',
    path: '/mentor/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorResourcesRoute =
  AuthenticatedMentorResourcesRouteImport.update({
    id: '/mentor/resources',
    path: '/mentor/resources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorSessionsRoute =
  AuthenticatedMentorSessionsRouteImport.update({
    id: '/mentor/sessions',
    path: '/mentor/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCheckoutRoute =
  AuthenticatedStudentCheckoutRouteImport.update({
    id: '/student/checkout',
    path: '/student/checkout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/student/dashboard',
    path: '/student/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentDemoConversionRoute =
  AuthenticatedStudentDemoConversionRouteImport.update({
    id: '/student/demo-conversion',
    path: '/student/demo-conversion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentDemoSessionRoute =
  AuthenticatedStudentDemoSessionRouteImport.update({
    id: '/student/demo-session',
    path: '/student/demo-session',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentExploreRoute =
  AuthenticatedStudentExploreRouteImport.update({
    id: '/student/explore',
    path: '/student/explore',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentHistoryRoute =
  AuthenticatedStudentHistoryRouteImport.update({
    id: '/student/history',
    path: '/student/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentPricingRoute =
  AuthenticatedStudentPricingRouteImport.update({
    id: '/student/pricing',
    path: '/student/pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/student/profile',
    path: '/student/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentResourcesRoute =
  AuthenticatedStudentResourcesRouteImport.update({
    id: '/student/resources',
    path: '/student/resources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentSessionsRoute =
  AuthenticatedStudentSessionsRouteImport.update({
    id: '/student/sessions',
    path: '/student/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentStreakRoute =
  AuthenticatedStudentStreakRouteImport.update({
    id: '/student/streak',
    path: '/student/streak',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentStudentSettingsRoute =
  AuthenticatedStudentStudentSettingsRouteImport.update({
    id: '/student/student-settings',
    path: '/student/student-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentSubscriptionSlotsRoute =
  AuthenticatedStudentSubscriptionSlotsRouteImport.update({
    id: '/student/subscription-slots',
    path: '/student/subscription-slots',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentSubscriptionsRoute =
  AuthenticatedStudentSubscriptionsRouteImport.update({
    id: '/student/subscriptions',
    path: '/student/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMentorApplicationsIdRoute =
  AuthenticatedAdminMentorApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminMentorApplicationsRoute,
  } as any)
const AuthenticatedMentorSessionIdRoute =
  AuthenticatedMentorSessionIdRouteImport.update({
    id: '/mentor/session/$id',
    path: '/mentor/session/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentMentorIdRoute =
  AuthenticatedStudentMentorIdRouteImport.update({
    id: '/student/mentor/$id',
    path: '/student/mentor/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentSessionIdRoute =
  AuthenticatedStudentSessionIdRouteImport.update({
    id: '/student/session/$id',
    path: '/student/session/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/become-a-mentor': typeof BecomeAMentorRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/mentor/apply': typeof MentorApplyRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/booking-queue': typeof AuthenticatedAdminBookingQueueRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/demo-queue': typeof AuthenticatedAdminDemoQueueRoute
  '/admin/mentor-applications': typeof AuthenticatedAdminMentorApplicationsRouteWithChildren
  '/admin/notification-broadcasts': typeof AuthenticatedAdminNotificationBroadcastsRoute
  '/admin/slot-management': typeof AuthenticatedAdminSlotManagementRoute
  '/admin/subscription-management': typeof AuthenticatedAdminSubscriptionManagementRoute
  '/admin/subscription-plans': typeof AuthenticatedAdminSubscriptionPlansRoute
  '/admin/support-tickets': typeof AuthenticatedAdminSupportTicketsRoute
  '/mentor/application': typeof AuthenticatedMentorApplicationRoute
  '/mentor/availability': typeof AuthenticatedMentorAvailabilityRoute
  '/mentor/calendar': typeof AuthenticatedMentorCalendarRoute
  '/mentor/dashboard': typeof AuthenticatedMentorDashboardRoute
  '/mentor/profile': typeof AuthenticatedMentorProfileRoute
  '/mentor/requests': typeof AuthenticatedMentorRequestsRoute
  '/mentor/resources': typeof AuthenticatedMentorResourcesRoute
  '/mentor/sessions': typeof AuthenticatedMentorSessionsRoute
  '/student/checkout': typeof AuthenticatedStudentCheckoutRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/demo-conversion': typeof AuthenticatedStudentDemoConversionRoute
  '/student/demo-session': typeof AuthenticatedStudentDemoSessionRoute
  '/student/explore': typeof AuthenticatedStudentExploreRoute
  '/student/history': typeof AuthenticatedStudentHistoryRoute
  '/student/pricing': typeof AuthenticatedStudentPricingRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/resources': typeof AuthenticatedStudentResourcesRoute
  '/student/sessions': typeof AuthenticatedStudentSessionsRoute
  '/student/streak': typeof AuthenticatedStudentStreakRoute
  '/student/student-settings': typeof AuthenticatedStudentStudentSettingsRoute
  '/student/subscription-slots': typeof AuthenticatedStudentSubscriptionSlotsRoute
  '/student/subscriptions': typeof AuthenticatedStudentSubscriptionsRoute
  '/admin/mentor-applications/$id': typeof AuthenticatedAdminMentorApplicationsIdRoute
  '/mentor/session/$id': typeof AuthenticatedMentorSessionIdRoute
  '/student/mentor/$id': typeof AuthenticatedStudentMentorIdRoute
  '/student/session/$id': typeof AuthenticatedStudentSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/become-a-mentor': typeof BecomeAMentorRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/mentor/apply': typeof MentorApplyRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/booking-queue': typeof AuthenticatedAdminBookingQueueRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/demo-queue': typeof AuthenticatedAdminDemoQueueRoute
  '/admin/mentor-applications': typeof AuthenticatedAdminMentorApplicationsRouteWithChildren
  '/admin/notification-broadcasts': typeof AuthenticatedAdminNotificationBroadcastsRoute
  '/admin/slot-management': typeof AuthenticatedAdminSlotManagementRoute
  '/admin/subscription-management': typeof AuthenticatedAdminSubscriptionManagementRoute
  '/admin/subscription-plans': typeof AuthenticatedAdminSubscriptionPlansRoute
  '/admin/support-tickets': typeof AuthenticatedAdminSupportTicketsRoute
  '/mentor/application': typeof AuthenticatedMentorApplicationRoute
  '/mentor/availability': typeof AuthenticatedMentorAvailabilityRoute
  '/mentor/calendar': typeof AuthenticatedMentorCalendarRoute
  '/mentor/dashboard': typeof AuthenticatedMentorDashboardRoute
  '/mentor/profile': typeof AuthenticatedMentorProfileRoute
  '/mentor/requests': typeof AuthenticatedMentorRequestsRoute
  '/mentor/resources': typeof AuthenticatedMentorResourcesRoute
  '/mentor/sessions': typeof AuthenticatedMentorSessionsRoute
  '/student/checkout': typeof AuthenticatedStudentCheckoutRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/demo-conversion': typeof AuthenticatedStudentDemoConversionRoute
  '/student/demo-session': typeof AuthenticatedStudentDemoSessionRoute
  '/student/explore': typeof AuthenticatedStudentExploreRoute
  '/student/history': typeof AuthenticatedStudentHistoryRoute
  '/student/pricing': typeof AuthenticatedStudentPricingRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/resources': typeof AuthenticatedStudentResourcesRoute
  '/student/sessions': typeof AuthenticatedStudentSessionsRoute
  '/student/streak': typeof AuthenticatedStudentStreakRoute
  '/student/student-settings': typeof AuthenticatedStudentStudentSettingsRoute
  '/student/subscription-slots': typeof AuthenticatedStudentSubscriptionSlotsRoute
  '/student/subscriptions': typeof AuthenticatedStudentSubscriptionsRoute
  '/admin/mentor-applications/$id': typeof AuthenticatedAdminMentorApplicationsIdRoute
  '/mentor/session/$id': typeof AuthenticatedMentorSessionIdRoute
  '/student/mentor/$id': typeof AuthenticatedStudentMentorIdRoute
  '/student/session/$id': typeof AuthenticatedStudentSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/become-a-mentor': typeof BecomeAMentorRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/mentor/apply': typeof MentorApplyRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/booking-queue': typeof AuthenticatedAdminBookingQueueRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/demo-queue': typeof AuthenticatedAdminDemoQueueRoute
  '/_authenticated/admin/mentor-applications': typeof AuthenticatedAdminMentorApplicationsRouteWithChildren
  '/_authenticated/admin/notification-broadcasts': typeof AuthenticatedAdminNotificationBroadcastsRoute
  '/_authenticated/admin/slot-management': typeof AuthenticatedAdminSlotManagementRoute
  '/_authenticated/admin/subscription-management': typeof AuthenticatedAdminSubscriptionManagementRoute
  '/_authenticated/admin/subscription-plans': typeof AuthenticatedAdminSubscriptionPlansRoute
  '/_authenticated/admin/support-tickets': typeof AuthenticatedAdminSupportTicketsRoute
  '/_authenticated/mentor/application': typeof AuthenticatedMentorApplicationRoute
  '/_authenticated/mentor/availability': typeof AuthenticatedMentorAvailabilityRoute
  '/_authenticated/mentor/calendar': typeof AuthenticatedMentorCalendarRoute
  '/_authenticated/mentor/dashboard': typeof AuthenticatedMentorDashboardRoute
  '/_authenticated/mentor/profile': typeof AuthenticatedMentorProfileRoute
  '/_authenticated/mentor/requests': typeof AuthenticatedMentorRequestsRoute
  '/_authenticated/mentor/resources': typeof AuthenticatedMentorResourcesRoute
  '/_authenticated/mentor/sessions': typeof AuthenticatedMentorSessionsRoute
  '/_authenticated/student/checkout': typeof AuthenticatedStudentCheckoutRoute
  '/_authenticated/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/student/demo-conversion': typeof AuthenticatedStudentDemoConversionRoute
  '/_authenticated/student/demo-session': typeof AuthenticatedStudentDemoSessionRoute
  '/_authenticated/student/explore': typeof AuthenticatedStudentExploreRoute
  '/_authenticated/student/history': typeof AuthenticatedStudentHistoryRoute
  '/_authenticated/student/pricing': typeof AuthenticatedStudentPricingRoute
  '/_authenticated/student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/student/resources': typeof AuthenticatedStudentResourcesRoute
  '/_authenticated/student/sessions': typeof AuthenticatedStudentSessionsRoute
  '/_authenticated/student/streak': typeof AuthenticatedStudentStreakRoute
  '/_authenticated/student/student-settings': typeof AuthenticatedStudentStudentSettingsRoute
  '/_authenticated/student/subscription-slots': typeof AuthenticatedStudentSubscriptionSlotsRoute
  '/_authenticated/student/subscriptions': typeof AuthenticatedStudentSubscriptionsRoute
  '/_authenticated/admin/mentor-applications/$id': typeof AuthenticatedAdminMentorApplicationsIdRoute
  '/_authenticated/mentor/session/$id': typeof AuthenticatedMentorSessionIdRoute
  '/_authenticated/student/mentor/$id': typeof AuthenticatedStudentMentorIdRoute
  '/_authenticated/student/session/$id': typeof AuthenticatedStudentSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/become-a-mentor'
    | '/login'
    | '/signup'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/auth/callback'
    | '/mentor/apply'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/booking-queue'
    | '/admin/dashboard'
    | '/admin/demo-queue'
    | '/admin/mentor-applications'
    | '/admin/notification-broadcasts'
    | '/admin/slot-management'
    | '/admin/subscription-management'
    | '/admin/subscription-plans'
    | '/admin/support-tickets'
    | '/mentor/application'
    | '/mentor/availability'
    | '/mentor/calendar'
    | '/mentor/dashboard'
    | '/mentor/profile'
    | '/mentor/requests'
    | '/mentor/resources'
    | '/mentor/sessions'
    | '/student/checkout'
    | '/student/dashboard'
    | '/student/demo-conversion'
    | '/student/demo-session'
    | '/student/explore'
    | '/student/history'
    | '/student/pricing'
    | '/student/profile'
    | '/student/resources'
    | '/student/sessions'
    | '/student/streak'
    | '/student/student-settings'
    | '/student/subscription-slots'
    | '/student/subscriptions'
    | '/admin/mentor-applications/$id'
    | '/mentor/session/$id'
    | '/student/mentor/$id'
    | '/student/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/become-a-mentor'
    | '/login'
    | '/signup'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/auth/callback'
    | '/mentor/apply'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/booking-queue'
    | '/admin/dashboard'
    | '/admin/demo-queue'
    | '/admin/mentor-applications'
    | '/admin/notification-broadcasts'
    | '/admin/slot-management'
    | '/admin/subscription-management'
    | '/admin/subscription-plans'
    | '/admin/support-tickets'
    | '/mentor/application'
    | '/mentor/availability'
    | '/mentor/calendar'
    | '/mentor/dashboard'
    | '/mentor/profile'
    | '/mentor/requests'
    | '/mentor/resources'
    | '/mentor/sessions'
    | '/student/checkout'
    | '/student/dashboard'
    | '/student/demo-conversion'
    | '/student/demo-session'
    | '/student/explore'
    | '/student/history'
    | '/student/pricing'
    | '/student/profile'
    | '/student/resources'
    | '/student/sessions'
    | '/student/streak'
    | '/student/student-settings'
    | '/student/subscription-slots'
    | '/student/subscriptions'
    | '/admin/mentor-applications/$id'
    | '/mentor/session/$id'
    | '/student/mentor/$id'
    | '/student/session/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/become-a-mentor'
    | '/login'
    | '/signup'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/mentor/apply'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/booking-queue'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/demo-queue'
    | '/_authenticated/admin/mentor-applications'
    | '/_authenticated/admin/notification-broadcasts'
    | '/_authenticated/admin/slot-management'
    | '/_authenticated/admin/subscription-management'
    | '/_authenticated/admin/subscription-plans'
    | '/_authenticated/admin/support-tickets'
    | '/_authenticated/mentor/application'
    | '/_authenticated/mentor/availability'
    | '/_authenticated/mentor/calendar'
    | '/_authenticated/mentor/dashboard'
    | '/_authenticated/mentor/profile'
    | '/_authenticated/mentor/requests'
    | '/_authenticated/mentor/resources'
    | '/_authenticated/mentor/sessions'
    | '/_authenticated/student/checkout'
    | '/_authenticated/student/dashboard'
    | '/_authenticated/student/demo-conversion'
    | '/_authenticated/student/demo-session'
    | '/_authenticated/student/explore'
    | '/_authenticated/student/history'
    | '/_authenticated/student/pricing'
    | '/_authenticated/student/profile'
    | '/_authenticated/student/resources'
    | '/_authenticated/student/sessions'
    | '/_authenticated/student/streak'
    | '/_authenticated/student/student-settings'
    | '/_authenticated/student/subscription-slots'
    | '/_authenticated/student/subscriptions'
    | '/_authenticated/admin/mentor-applications/$id'
    | '/_authenticated/mentor/session/$id'
    | '/_authenticated/student/mentor/$id'
    | '/_authenticated/student/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BecomeAMentorRoute: typeof BecomeAMentorRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  MentorApplyRoute: typeof MentorApplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-mentor': {
      id: '/become-a-mentor'
      path: '/become-a-mentor'
      fullPath: '/become-a-mentor'
      preLoaderRoute: typeof BecomeAMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/mentor/apply': {
      id: '/mentor/apply'
      path: '/mentor/apply'
      fullPath: '/mentor/apply'
      preLoaderRoute: typeof MentorApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/booking-queue': {
      id: '/_authenticated/admin/booking-queue'
      path: '/admin/booking-queue'
      fullPath: '/admin/booking-queue'
      preLoaderRoute: typeof AuthenticatedAdminBookingQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/demo-queue': {
      id: '/_authenticated/admin/demo-queue'
      path: '/admin/demo-queue'
      fullPath: '/admin/demo-queue'
      preLoaderRoute: typeof AuthenticatedAdminDemoQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/mentor-applications': {
      id: '/_authenticated/admin/mentor-applications'
      path: '/admin/mentor-applications'
      fullPath: '/admin/mentor-applications'
      preLoaderRoute: typeof AuthenticatedAdminMentorApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notification-broadcasts': {
      id: '/_authenticated/admin/notification-broadcasts'
      path: '/admin/notification-broadcasts'
      fullPath: '/admin/notification-broadcasts'
      preLoaderRoute: typeof AuthenticatedAdminNotificationBroadcastsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/slot-management': {
      id: '/_authenticated/admin/slot-management'
      path: '/admin/slot-management'
      fullPath: '/admin/slot-management'
      preLoaderRoute: typeof AuthenticatedAdminSlotManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/subscription-management': {
      id: '/_authenticated/admin/subscription-management'
      path: '/admin/subscription-management'
      fullPath: '/admin/subscription-management'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/subscription-plans': {
      id: '/_authenticated/admin/subscription-plans'
      path: '/admin/subscription-plans'
      fullPath: '/admin/subscription-plans'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/support-tickets': {
      id: '/_authenticated/admin/support-tickets'
      path: '/admin/support-tickets'
      fullPath: '/admin/support-tickets'
      preLoaderRoute: typeof AuthenticatedAdminSupportTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/application': {
      id: '/_authenticated/mentor/application'
      path: '/mentor/application'
      fullPath: '/mentor/application'
      preLoaderRoute: typeof AuthenticatedMentorApplicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/availability': {
      id: '/_authenticated/mentor/availability'
      path: '/mentor/availability'
      fullPath: '/mentor/availability'
      preLoaderRoute: typeof AuthenticatedMentorAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/calendar': {
      id: '/_authenticated/mentor/calendar'
      path: '/mentor/calendar'
      fullPath: '/mentor/calendar'
      preLoaderRoute: typeof AuthenticatedMentorCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/dashboard': {
      id: '/_authenticated/mentor/dashboard'
      path: '/mentor/dashboard'
      fullPath: '/mentor/dashboard'
      preLoaderRoute: typeof AuthenticatedMentorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/profile': {
      id: '/_authenticated/mentor/profile'
      path: '/mentor/profile'
      fullPath: '/mentor/profile'
      preLoaderRoute: typeof AuthenticatedMentorProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/requests': {
      id: '/_authenticated/mentor/requests'
      path: '/mentor/requests'
      fullPath: '/mentor/requests'
      preLoaderRoute: typeof AuthenticatedMentorRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/resources': {
      id: '/_authenticated/mentor/resources'
      path: '/mentor/resources'
      fullPath: '/mentor/resources'
      preLoaderRoute: typeof AuthenticatedMentorResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor/sessions': {
      id: '/_authenticated/mentor/sessions'
      path: '/mentor/sessions'
      fullPath: '/mentor/sessions'
      preLoaderRoute: typeof AuthenticatedMentorSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/checkout': {
      id: '/_authenticated/student/checkout'
      path: '/student/checkout'
      fullPath: '/student/checkout'
      preLoaderRoute: typeof AuthenticatedStudentCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/dashboard': {
      id: '/_authenticated/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/demo-conversion': {
      id: '/_authenticated/student/demo-conversion'
      path: '/student/demo-conversion'
      fullPath: '/student/demo-conversion'
      preLoaderRoute: typeof AuthenticatedStudentDemoConversionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/demo-session': {
      id: '/_authenticated/student/demo-session'
      path: '/student/demo-session'
      fullPath: '/student/demo-session'
      preLoaderRoute: typeof AuthenticatedStudentDemoSessionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/explore': {
      id: '/_authenticated/student/explore'
      path: '/student/explore'
      fullPath: '/student/explore'
      preLoaderRoute: typeof AuthenticatedStudentExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/history': {
      id: '/_authenticated/student/history'
      path: '/student/history'
      fullPath: '/student/history'
      preLoaderRoute: typeof AuthenticatedStudentHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/pricing': {
      id: '/_authenticated/student/pricing'
      path: '/student/pricing'
      fullPath: '/student/pricing'
      preLoaderRoute: typeof AuthenticatedStudentPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/profile': {
      id: '/_authenticated/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/resources': {
      id: '/_authenticated/student/resources'
      path: '/student/resources'
      fullPath: '/student/resources'
      preLoaderRoute: typeof AuthenticatedStudentResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/sessions': {
      id: '/_authenticated/student/sessions'
      path: '/student/sessions'
      fullPath: '/student/sessions'
      preLoaderRoute: typeof AuthenticatedStudentSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/streak': {
      id: '/_authenticated/student/streak'
      path: '/student/streak'
      fullPath: '/student/streak'
      preLoaderRoute: typeof AuthenticatedStudentStreakRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/student-settings': {
      id: '/_authenticated/student/student-settings'
      path: '/student/student-settings'
      fullPath: '/student/student-settings'
      preLoaderRoute: typeof AuthenticatedStudentStudentSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/subscription-slots': {
      id: '/_authenticated/student/subscription-slots'
      path: '/student/subscription-slots'
      fullPath: '/student/subscription-slots'
      preLoaderRoute: typeof AuthenticatedStudentSubscriptionSlotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/subscriptions': {
      id: '/_authenticated/student/subscriptions'
      path: '/student/subscriptions'
      fullPath: '/student/subscriptions'
      preLoaderRoute: typeof AuthenticatedStudentSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/mentor-applications/$id': {
      id: '/_authenticated/admin/mentor-applications/$id'
      path: '/$id'
      fullPath: '/admin/mentor-applications/$id'
      preLoaderRoute: typeof AuthenticatedAdminMentorApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedAdminMentorApplicationsRoute
    }
    '/_authenticated/mentor/session/$id': {
      id: '/_authenticated/mentor/session/$id'
      path: '/mentor/session/$id'
      fullPath: '/mentor/session/$id'
      preLoaderRoute: typeof AuthenticatedMentorSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/mentor/$id': {
      id: '/_authenticated/student/mentor/$id'
      path: '/student/mentor/$id'
      fullPath: '/student/mentor/$id'
      preLoaderRoute: typeof AuthenticatedStudentMentorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/session/$id': {
      id: '/_authenticated/student/session/$id'
      path: '/student/session/$id'
      fullPath: '/student/session/$id'
      preLoaderRoute: typeof AuthenticatedStudentSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminMentorApplicationsRouteChildren {
  AuthenticatedAdminMentorApplicationsIdRoute: typeof AuthenticatedAdminMentorApplicationsIdRoute
}

const AuthenticatedAdminMentorApplicationsRouteChildren: AuthenticatedAdminMentorApplicationsRouteChildren =
  {
    AuthenticatedAdminMentorApplicationsIdRoute:
      AuthenticatedAdminMentorApplicationsIdRoute,
  }

const AuthenticatedAdminMentorApplicationsRouteWithChildren =
  AuthenticatedAdminMentorApplicationsRoute._addFileChildren(
    AuthenticatedAdminMentorApplicationsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminBookingQueueRoute: typeof AuthenticatedAdminBookingQueueRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDemoQueueRoute: typeof AuthenticatedAdminDemoQueueRoute
  AuthenticatedAdminMentorApplicationsRoute: typeof AuthenticatedAdminMentorApplicationsRouteWithChildren
  AuthenticatedAdminNotificationBroadcastsRoute: typeof AuthenticatedAdminNotificationBroadcastsRoute
  AuthenticatedAdminSlotManagementRoute: typeof AuthenticatedAdminSlotManagementRoute
  AuthenticatedAdminSubscriptionManagementRoute: typeof AuthenticatedAdminSubscriptionManagementRoute
  AuthenticatedAdminSubscriptionPlansRoute: typeof AuthenticatedAdminSubscriptionPlansRoute
  AuthenticatedAdminSupportTicketsRoute: typeof AuthenticatedAdminSupportTicketsRoute
  AuthenticatedMentorApplicationRoute: typeof AuthenticatedMentorApplicationRoute
  AuthenticatedMentorAvailabilityRoute: typeof AuthenticatedMentorAvailabilityRoute
  AuthenticatedMentorCalendarRoute: typeof AuthenticatedMentorCalendarRoute
  AuthenticatedMentorDashboardRoute: typeof AuthenticatedMentorDashboardRoute
  AuthenticatedMentorProfileRoute: typeof AuthenticatedMentorProfileRoute
  AuthenticatedMentorRequestsRoute: typeof AuthenticatedMentorRequestsRoute
  AuthenticatedMentorResourcesRoute: typeof AuthenticatedMentorResourcesRoute
  AuthenticatedMentorSessionsRoute: typeof AuthenticatedMentorSessionsRoute
  AuthenticatedStudentCheckoutRoute: typeof AuthenticatedStudentCheckoutRoute
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentDemoConversionRoute: typeof AuthenticatedStudentDemoConversionRoute
  AuthenticatedStudentDemoSessionRoute: typeof AuthenticatedStudentDemoSessionRoute
  AuthenticatedStudentExploreRoute: typeof AuthenticatedStudentExploreRoute
  AuthenticatedStudentHistoryRoute: typeof AuthenticatedStudentHistoryRoute
  AuthenticatedStudentPricingRoute: typeof AuthenticatedStudentPricingRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentResourcesRoute: typeof AuthenticatedStudentResourcesRoute
  AuthenticatedStudentSessionsRoute: typeof AuthenticatedStudentSessionsRoute
  AuthenticatedStudentStreakRoute: typeof AuthenticatedStudentStreakRoute
  AuthenticatedStudentStudentSettingsRoute: typeof AuthenticatedStudentStudentSettingsRoute
  AuthenticatedStudentSubscriptionSlotsRoute: typeof AuthenticatedStudentSubscriptionSlotsRoute
  AuthenticatedStudentSubscriptionsRoute: typeof AuthenticatedStudentSubscriptionsRoute
  AuthenticatedMentorSessionIdRoute: typeof AuthenticatedMentorSessionIdRoute
  AuthenticatedStudentMentorIdRoute: typeof AuthenticatedStudentMentorIdRoute
  AuthenticatedStudentSessionIdRoute: typeof AuthenticatedStudentSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminBookingQueueRoute: AuthenticatedAdminBookingQueueRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDemoQueueRoute: AuthenticatedAdminDemoQueueRoute,
  AuthenticatedAdminMentorApplicationsRoute:
    AuthenticatedAdminMentorApplicationsRouteWithChildren,
  AuthenticatedAdminNotificationBroadcastsRoute:
    AuthenticatedAdminNotificationBroadcastsRoute,
  AuthenticatedAdminSlotManagementRoute: AuthenticatedAdminSlotManagementRoute,
  AuthenticatedAdminSubscriptionManagementRoute:
    AuthenticatedAdminSubscriptionManagementRoute,
  AuthenticatedAdminSubscriptionPlansRoute:
    AuthenticatedAdminSubscriptionPlansRoute,
  AuthenticatedAdminSupportTicketsRoute: AuthenticatedAdminSupportTicketsRoute,
  AuthenticatedMentorApplicationRoute: AuthenticatedMentorApplicationRoute,
  AuthenticatedMentorAvailabilityRoute: AuthenticatedMentorAvailabilityRoute,
  AuthenticatedMentorCalendarRoute: AuthenticatedMentorCalendarRoute,
  AuthenticatedMentorDashboardRoute: AuthenticatedMentorDashboardRoute,
  AuthenticatedMentorProfileRoute: AuthenticatedMentorProfileRoute,
  AuthenticatedMentorRequestsRoute: AuthenticatedMentorRequestsRoute,
  AuthenticatedMentorResourcesRoute: AuthenticatedMentorResourcesRoute,
  AuthenticatedMentorSessionsRoute: AuthenticatedMentorSessionsRoute,
  AuthenticatedStudentCheckoutRoute: AuthenticatedStudentCheckoutRoute,
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedStudentDemoConversionRoute:
    AuthenticatedStudentDemoConversionRoute,
  AuthenticatedStudentDemoSessionRoute: AuthenticatedStudentDemoSessionRoute,
  AuthenticatedStudentExploreRoute: AuthenticatedStudentExploreRoute,
  AuthenticatedStudentHistoryRoute: AuthenticatedStudentHistoryRoute,
  AuthenticatedStudentPricingRoute: AuthenticatedStudentPricingRoute,
  AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
  AuthenticatedStudentResourcesRoute: AuthenticatedStudentResourcesRoute,
  AuthenticatedStudentSessionsRoute: AuthenticatedStudentSessionsRoute,
  AuthenticatedStudentStreakRoute: AuthenticatedStudentStreakRoute,
  AuthenticatedStudentStudentSettingsRoute:
    AuthenticatedStudentStudentSettingsRoute,
  AuthenticatedStudentSubscriptionSlotsRoute:
    AuthenticatedStudentSubscriptionSlotsRoute,
  AuthenticatedStudentSubscriptionsRoute:
    AuthenticatedStudentSubscriptionsRoute,
  AuthenticatedMentorSessionIdRoute: AuthenticatedMentorSessionIdRoute,
  AuthenticatedStudentMentorIdRoute: AuthenticatedStudentMentorIdRoute,
  AuthenticatedStudentSessionIdRoute: AuthenticatedStudentSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BecomeAMentorRoute: BecomeAMentorRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  MentorApplyRoute: MentorApplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
